apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parks-app
  namespace: {{ .Values.cicdNs }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.appNs }}
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: .
