kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-{{ .Release.name }}
  namespace: {{ .Values.appNs }}
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: {{ .Values.cicdNs }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
