# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## You MUST specify a hostname
# hostname: gitea.apps.mycluster.openshiftapps.com

## Override where the gitea container image is pulling from
# imagestream_from: quay.io/gpte-devops-automation/gitea:latest
# imagestream_name: gitea
# imagestring_tag: latest

# repository_size: 1Gi

# secret_key: '8 character hard to guess alpha string'
# internal_token: '106 character hard to guess string'

# https://docs.gitea.io/en-us/signing/#signing_key
# none, default or KEYID
signing: default

## YOU MUST SPECIFY THE DB PASSWORD!!!
db: {}
#   password: 'xxxx'
#   name: gitea-db
#   user: gitea
#   imagestream_name: postgresql
#   imagestream_namespace: openshift
#   imagestream_tag: latest
