apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.channel | quote }}
  installPlanApproval: Automatic
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.startingCSV }}
