apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.name | default "gitea" | quote }}
  name: "{{ .Values.name | default "gitea" }}-repositories"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.repository_size | default "5Gi" | quote }}
