apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name | default "gitea-db" | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size | default "1Gi" | quote }}
