apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The Gitea server's http port
  labels:
    app: {{ .Values.name | default "gitea" | quote }}
  name: {{ .Values.name | default "gitea" | quote }}
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.name | default "gitea" | quote }}
    deploymentconfig: {{ .Values.name | default "gitea" | quote }}
  sessionAffinity: None
  type: ClusterIP
